# Generated by Django 3.2 on 2021-04-17 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='square_field',
            new_name='square_feet',
        ),
    ]
